#!/usr/bin/env python3
"""Read the Neo4j ontology POC, emit SQL for the v3 Postgres schema on stdout.

    python3 transfer.py > 03_transfer.sql
    docker exec -i ontology-pg psql -U ontology -d ontology -v ON_ERROR_STOP=1 -f - < 03_transfer.sql

Mapping decisions (all noted in the report):
  (:Term)                               -> entities(kind='Term')
  Term.name                             -> entities.name (the canonical name)
  (:Term)-[:HAS_CATEGORY]->(:Category)  -> entities.category_id     (FK, not an edge)
  (:Term)-[:HAS_CHANGE]->(:Change)      -> review_events            (FK, not an edge)
  (:Draft)-[:DRAFT_OF]->(:Term)         -> drafts                   (FK, not an edge)
  everything else                       -> relations
"""
import os
import sys
from neo4j import GraphDatabase

URI = os.environ.get("NEO4J_URI", "bolt://localhost:7688")
AUTH = (os.environ.get("NEO4J_USER", "neo4j"), os.environ.get("NEO4J_PASSWORD", "123456@a"))

# these Neo4j relationship types become columns, not rows in `relations`
STRUCTURAL = {"HAS_CATEGORY", "HAS_CHANGE", "DRAFT_OF"}


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def ts(v):
    """Neo4j DateTime -> timestamptz literal."""
    return "NULL" if v is None else q(v.isoformat())


def main():
    out = []
    w = out.append
    notes = []

    with GraphDatabase.driver(URI, auth=AUTH) as d, d.session() as s:
        users = {r["email"]: r["role"] for r in s.run(
            "MATCH (u:User) RETURN u.email AS email, u.role AS role")}
        cats = [r["name"] for r in s.run(
            "MATCH (c:Category) RETURN c.name AS name ORDER BY c.name")]
        terms = [dict(r) for r in s.run("""
            MATCH (t:Term)
            OPTIONAL MATCH (t)-[:HAS_CATEGORY]->(c:Category)
            OPTIONAL MATCH (t)-[:HAS_CHANGE]->(x:Change {action:'approve_new'})
            RETURN elementId(t) AS eid, t.name AS name, t.definition AS definition,
                   t.formula AS formula, t.status AS status, t.version AS version,
                   t.createdBy AS created_by, c.name AS category,
                   min(x.changedAt) AS published_at
            ORDER BY t.name""")]
        rels = [dict(r) for r in s.run("""
            MATCH (a:Term)-[r]->(b:Term)
            RETURN elementId(a) AS src, type(r) AS pred, elementId(b) AS dst
            ORDER BY type(r)""")]
        changes = [dict(r) for r in s.run("""
            MATCH (c:Change)
            OPTIONAL MATCH (t:Term)-[:HAS_CHANGE]->(c)
            RETURN elementId(t) AS eid, t.name AS term_name, c.action AS action,
                   c.field AS field, c.oldValue AS old_value, c.newValue AS new_value,
                   c.reason AS reason, c.changedBy AS actor, c.changedAt AS at
            ORDER BY c.changedAt""")]
        drafts = [dict(r) for r in s.run("""
            MATCH (d:Draft)-[:DRAFT_OF]->(t:Term)
            RETURN elementId(t) AS eid, t.name AS term_name, t.version AS base_version,
                   t.createdBy AS term_author, d.definition AS definition,
                   d.formula AS formula, d.status AS status""")]

    # actors that appear in the audit trail but have no :User node
    ghosts = sorted({c["actor"] for c in changes if c["actor"]} - set(users))
    if ghosts:
        notes.append("audit actors with no :User node, imported as role=viewer: "
                     + ", ".join(ghosts))

    w("-- generated by transfer.py from " + URI)
    w("BEGIN;")

    w("\n-- users")
    for email, role in sorted(users.items()):
        w(f"INSERT INTO users (email, role) VALUES ({q(email)}, {q(role)});")
    for email in ghosts:
        w(f"INSERT INTO users (email, role) VALUES ({q(email)}, 'viewer');")

    w("\n-- categories")
    for c in cats:
        w(f"INSERT INTO categories (name) VALUES ({q(c)});")

    w("\n-- entities: every Neo4j :Term becomes kind='Term', carrying its own name")
    for t in terms:
        cat = ("(SELECT id FROM categories WHERE name = %s)" % q(t["category"])
               if t["category"] else "NULL")
        created = ts(t["published_at"])
        w("INSERT INTO entities (id, kind, name, name_lang, definition, formula, status, "
          "version, created_by, category_id, created_at, updated_at) VALUES "
          f"(gen_random_uuid(), 'Term', {q(t['name'])}, 'vi', {q(t['definition'])}, "
          f"{q(t['formula'])}, {q(t['status'])}, {t['version']}, {q(t['created_by'])}, {cat}, "
          f"coalesce({created}, now()), coalesce({created}, now()));")

    w("\n-- relations")
    eid_of = {t["eid"]: t["name"] for t in terms}
    for r in rels:
        if r["pred"] in STRUCTURAL:
            continue
        w("INSERT INTO relations (subject_id, predicate, object_id, created_by) "
          f"SELECT a.id, {q(r['pred'])}, b.id, 'admin@corp.com' "
          f"FROM terms a, terms b WHERE a.name = {q(eid_of[r['src']])} "
          f"AND b.name = {q(eid_of[r['dst']])};")

    w("\n-- pending drafts")
    for d in drafts:
        patch = {}
        if d["definition"] is not None:
            patch["definition"] = d["definition"]
        if d["formula"] is not None:
            patch["formula"] = d["formula"]
        import json
        w("INSERT INTO drafts (entity_id, base_version, patch, status, author) "
          f"SELECT id, {d['base_version']}, {q(json.dumps(patch, ensure_ascii=False))}::jsonb, "
          f"{q(d['status'])}, {q(d['term_author'])} FROM terms WHERE name = {q(d['term_name'])};")
        notes.append(f"draft on {d['term_name']!r}: Neo4j stores no author, "
                     f"imported as the term's creator ({d['term_author']})")

    w("\n-- workflow audit trail (term_name is snapshotted so orphans survive)")
    for c in changes:
        term_ref = (f"(SELECT id FROM terms WHERE name = {q(c['term_name'])})"
                    if c["eid"] else "NULL")
        w("INSERT INTO review_events (entity_id, entity_name, action, field, old_value, "
          f"new_value, reason, actor, at) VALUES ({term_ref}, {q(c['term_name'])}, "
          f"{q(c['action'])}, {q(c['field'])}, {q(c['old_value'])}, {q(c['new_value'])}, "
          f"{q(c['reason'])}, {q(c['actor'])}, {ts(c['at'])});")

    w("\nCOMMIT;")

    print("\n".join(out))
    for n in notes:
        print("-- NOTE: " + n, file=sys.stderr)
    print(f"-- counts: users={len(users)+len(ghosts)} categories={len(cats)} "
          f"entities={len(terms)} (all kind=Term) relations={sum(1 for r in rels if r['pred'] not in STRUCTURAL)} "
          f"drafts={len(drafts)} events={len(changes)}", file=sys.stderr)


if __name__ == "__main__":
    main()
